name: deepclimb
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
# worked on Python 3.7.1
  - python >= 3.7
  - pip
  - numpy
# to save data files (especially np.array)
  - ujson
# to display progress bar
  - tqdm
# to scrap the data
  - selenium=3.141
 # to handle images
  - Pillow
# for deep learning
# worked on PyTorch 1.0.1
  - pytorch>=1.0.0
# to display training curves in real time
  - tensorboard
#  - tensorflow
  - tensorboardX
  - pip:
    - torch>=1.0.0
    - torchvision