name: deepclimb
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
# TODO: check version on GCloud
  - python=3.6
  - pip
  - numpy
# to save data files (especially np.array)
  - ujson
# to display progress bar
  - tqdm
# to scrap the data
  - selenium=3.141
 # to handle images
  - Pillow
# for deep learning
# TODO: check version on GCloud
  - pytorch=1.0.0
# to display training curves in real time
  - tensorboard
  - tensorflow
  - tensorboardX
  - pip:
# TODO: check version on GCloud
    - torch==1.0.0